In [1]:
#Importing libraries
import numpy as np 
import pandas as pd 
import io
import matplotlib.pyplot as plt

In [2]:
# reading the csv file, del 2 columns from the file, checking first few rows of the file
from google.colab import files
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))

data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer.csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
#Declare label as last column in the source file
label=data['Purchased']
label

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [4]:
#Declaring X as all columns excluding last
X=data[['Age','EstimatedSalary']]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [5]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,label,test_size=0.3,random_state=14)
X_train, X_test, y_train, y_test

(     Age  EstimatedSalary
 303   37            79000
 186   20            82000
 342   38            65000
 111   37            71000
 183   33            43000
 ..   ...              ...
 249   35            97000
 327   42            75000
 268   47           144000
 344   47           105000
 107   27            89000
 
 [280 rows x 2 columns],      Age  EstimatedSalary
 85    31           118000
 20    45            22000
 1     35            20000
 346   53            72000
 69    31            68000
 ..   ...              ...
 94    29            83000
 190   24            84000
 125   39            61000
 222   37           144000
 132   30            87000
 
 [120 rows x 2 columns], 303    1
 186    0
 342    0
 111    0
 183    0
       ..
 249    1
 327    0
 268    1
 344    1
 107    0
 Name: Purchased, Length: 280, dtype: int64, 85     1
 20     1
 1      0
 346    1
 69     0
       ..
 94     0
 190    0
 125    0
 222    1
 132    0
 Name: Purchased, Length: 120, dtype

In [6]:
# Sacaling data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [8]:
entries = len(X_train[:,0])
entries

280

In [9]:
for weights in range(len_x):
    w.append(0)
w

[0, 0]

In [10]:
# Sigmoid function
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [11]:

def predict(inputs,w):
    z=np.dot(inputs,w)
    return sigmoid(z)

In [12]:
def loss_func(features,labels,w):
    observations = len(labels)
    predictions = predict(features, w)
    class1_cost = -labels*np.log(predictions)
    class2_cost = (1-labels)*np.log(1-predictions)
    cost = class1_cost - class2_cost
    cost = cost.sum() / observations
    return cost        

In [13]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

def update_weights(features, labels, weights, lr):    
    
    N = len(features)    
    predictions = predict(features, weights)    
    gradient = np.dot(features.T,  predictions - labels)    
    gradient /= N    
    gradient *= lr    
    weights -= gradient

    return weights

In [14]:
#Repeating the process 3000 times
cost_history = []
for i in range(3000):
    w = update_weights(X, label, w, alpha)

    #Calculate error for auditing purposes
    cost = loss_func(X, label, w)
    cost_history.append(cost)

    # Log Progress
    if i % 1000 == 0:
        print("iter: "+ str(i) + " cost: "+str(cost))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in log
  """


iter: 0 cost: inf
iter: 1000 cost: inf
iter: 2000 cost: inf


In [15]:
#Print weight
w

array([ -19.43575, 1407.375  ])

In [16]:
#print bias
b

0.2

In [17]:
#predicting the label
predicted_labels=predict(X_test,w)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
#print actual and predicted values in a table
predicted_labels,label


(array([1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        4.10470864e-256, 0.00000000e+000, 1.00000000e+000, 1.04738611e-242,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 1.00000000e+000, 1.00000000e+000,
        8.15039615e-190, 1.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        1.00000000e+000, 1.91134807e-191, 1.00000000e+000, 1.00000000e+000,
        6.29407677e-109, 1.00000000e+000, 1.00000000e+000, 2.07227834e-224,
        1.00

In [19]:
# Calculating accuracy of prediction
diff = predicted_labels - y_test
acc=1.0 - (float(np.count_nonzero(diff)) / len(diff))
acc

0.41666666666666663

#Using sklearn LogisticRegression model

In [20]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)

#Fit
LR=LR.fit(X_train,y_train)


#predicting the test label with LR. Predict always takes X as input
y_pred=LR.predict(X_test)
y_pred


array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

**Exercise:**

Try logistic regression on BuyComputer dataset and set Random state=Your_RollNumber (last 3 digit of ID, incase if you don't have ID)